nodeLinker: pnp
enableTelemetry: false
pnpEnableEsmLoader: false
pnpEnableInlining: false

packageExtensions:
  # missing dependency
  'react-dnd@*':
    dependencies:
      '@react-dnd/invariant': '^2.0.0'
