version: "3.1"

services:
  test_frontend:
    image: ${IMAGE_CI}-dev
    user: node
    environment:
      NODE_OPTIONS: "--trace-deprecation --enable-source-maps"
      NODE_ENV: test
      # Disable ansi-color output, it breaks the xunit xml parser in Jenkins.
      # https://github.com/chalk/chalk/blob/v4.1.0/readme.md#chalksupportscolor
      FORCE_COLOR: '0'
    entrypoint:
      - yarn
      - mocha
      - --exit
      - --delay
      - --reporter
      - xunit
      - --reporter-options
      - output=/home/node/jsdom.xml,suiteName='JSDOMTests'
      - test/frontend/buildAndRun.js
    volumes:
      - ./output:/home/node:z
    network_mode: none
