ARG IMAGE_CMD
ARG IMAGE_YARN
FROM $IMAGE_CMD as cmd
FROM $IMAGE_YARN

WORKDIR /overleaf/services/web

COPY docker_cleanup.sh /
COPY package.json yarn.lock .yarnrc.yml ./
COPY frontend/js/packages/react-i18next ./frontend/js/packages/react-i18next

ENV CYPRESS_INSTALL_BINARY=0
RUN /docker_cleanup.sh yarn install

COPY --from=cmd /usr/local/bin/frontend-build /usr/local/bin/
