version: "3.1"

services:
  test_frontend:
    image: node:18.14.1
    user: node
    volumes:
      - .:/overleaf/services/web
    working_dir: /overleaf/services/web
    command: npm run test:frontend
    environment:
      MOCHA_GREP: ${MOCHA_GREP}
      NODE_OPTIONS: "--unhandled-rejections=strict --trace-deprecation --enable-source-maps"
    network_mode: none
