version: "3.1"

services:
  test_frontend:
    image: ${IMAGE_YARN}
    user: node
    volumes:
      - .:/overleaf/services/web
    working_dir: /overleaf/services/web
    environment:
      NODE_OPTIONS: "--trace-deprecation --enable-source-maps"
      NODE_ENV: test
    entrypoint:
      - yarn
      - mocha
      - --exit
      - --delay
      - --grep=${MOCHA_GREP:-}
      - test/frontend/buildAndRun.js
    network_mode: none
